### ISSUE TITLE
Hi, can you share your table 1 implement configuration?

### ISSUE THREAD

**Issue by pc-cp** [wjun0830/Localizable-Rotation#1]
You've perfectly integrated self-supervision into supervised learning through multi-task learning, in a similar way to SLA! But I was not clear about your experimental setup when I reproduced Table 1 (CIFAR, Classification), so if you would like to provide a version of the implementation or some details, it would be appreciated!

**Comment by wjun0830** [comment]
Hello. Thanks for your interest in our work.

For the Tab. 1 setup, we used ResNet50 and the cosine scheduler.
For other details, I am very sorry that we have not recorded all our setups.

**Comment by pc-cp** [comment]
ok，Thanks for help!
