### ISSUE TITLE
Adversarial Perturbation Implementation

### ISSUE THREAD

**Issue by aristorenaldo** [wjun0830/Localizable-Rotation#2]
Hello, 
I want to ask about the implementation of the PGD attack. From the original implementation of PGD attack that you mention in the paper, calculating the perturbed image uses the gradient of the loss from classifier and auxilliary rotation. Is the Lorot loss value used in PGD or does it only use the loss from the classifier? Then, what is the ratio of the Lorot loss used in PGD?

Thank you

**Comment by wjun0830** [comment]
Yes, it uses the gradient from both classifiers, but I remember that there were differences in that LoRot does not use an extra batch of data to be rotated. The ratio of LoRot was 0.1.

**Comment by aristorenaldo** [comment]
Ok noted, thank you for your replies. One more question, how many epochs did you use for PGD training?

**Comment by wjun0830** [comment]
We've trained the model for 200 epochs

2023년 5월 28일 (일) 오후 9:25, Aristo Renaldo ***@***.***>님이 작성:

**Comment by aristorenaldo** [comment]
Ok, thanks for help
