### ISSUE TITLE
 Question about having 4 same rotation types

### ISSUE THREAD

**Issue by summersnowfish** [wjun0830/Localizable-Rotation#3]
Hello, thank you very much for your great work!
I have a doubtful question that I would like to ask you. In the ood_lorot-E file, you use idx to control which part of the image is rotated (a total of four parts), and use idx2 to control the angle of rotation, right? After doing so it will be divided into 16 categories. But I think when the value of idx2 is 0, no matter what idx is, the picture will not be rotated, right? In other words, there are 4 situations in which rotation does not occur. So how does the model distinguish between these 4 situations? I hope you can answer my questions despite your busy schedule. Thank you very much!

**Comment by wjun0830** [comment]
Thanks for the interest. 
In the paper, we indicated as "Note that, for LoRot-E, we keep redundant cases with 0◦at every cell as we pursue to place more weights on the original image."

As can be noticed in the paper, LoRot-E triggers more distribution shift compared to LoRot-I.
And that is why we pursued to put more weights on the original image.

**Comment by summersnowfish** [comment]
thank you for your reply. I'm sorry that I didn't read the paper carefully enough.
Best wishes for you!
